name: Build Project

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install ARM GNU Toolchain 15.2.Rel1
        run: |
          sudo apt-get update
          sudo apt-get install -y wget tar gzip
          wget https://developer.arm.com/-/media/Files/downloads/gnu/15.2.rel1/binrel/arm-gnu-toolchain-15.2.rel1-x86_64-arm-none-eabi.tar.xz -O arm-toolchain.tar.xz
          tar -xf arm-toolchain.tar.xz -C /opt/
          echo "/opt/arm-gnu-toolchain-15.2.rel1-x86_64-arm-none-eabi/bin" >> $GITHUB_PATH

      - name: Verify ARM GCC Installation
        run: |
          arm-none-eabi-gcc --version
          arm-none-eabi-g++ --version

      - name: Remove system CMake
        run: sudo apt-get purge -y cmake

      - name: Install CMake 4.2.3 (binary)
        run: |
          version=4.2.3
          wget https://github.com/Kitware/CMake/releases/download/v$version/cmake-$version-linux-x86_64.tar.gz -O cmake.tar.gz
          sudo tar -xzf cmake.tar.gz -C /opt/
          echo "/opt/cmake-$version-linux-x86_64/bin" >> $GITHUB_PATH

      - name: Verify CMake Installation
        run: cmake --version

      - name: Configure CMake
        run: |
          cmake --preset "Embedded2026 Debug"

      - name: Build project
        run: |
          cmake --build --preset "Embedded2026 Debug"

      - name: Check build artifacts
        run: |
          ls -la build/
